import React, { useEffect } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import MainCard from '../src/atomic/atoms/MainCard'
import MainTitle from '../src/atomic/atoms/MainTitle'
import ItemCard from '../src/atomic/molecules/ItemCard'
import { getAllCharacteres } from '../src/services'
import MainGrid from '../src/atomic/molecules/MainGrid'
import { useAppSelector, useAppDispatch } from '../src/store'
import { setCharacters } from '../src/store/slices/characters'
import { MortyEyeFollower } from '../src/atomic/molecules/MortyEyeFollower'

const Home: NextPage = () => {
  const characters = useAppSelector(
    (state) => state.charactersReducer.characters
  )
  const dispatch = useAppDispatch()

  useEffect(() => {
    getAllCharacteres().then(({ characters: chars }) =>
      dispatch(setCharacters(chars))
    )
  }, [dispatch])
  return (
    <>
      <Head>
        <title>Rick and Morty Web App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <MainCard>
        <MainTitle>Rick and Morty Web App</MainTitle>
        <MainGrid>
          {characters?.map?.((char) => (
            <ItemCard key={char.id} char={char} />
          ))}
        </MainGrid>
        <MortyEyeFollower />
      </MainCard>
    </>
  )
}
export default Home
