import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import MainCard from '../src/atomic/atoms/MainCard'
import MainTitle from '../src/atomic/atoms/MainTitle'
import ItemCard from '../src/atomic/molecules/ItemCard'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Rick and Morty Web App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <MainCard>
          <MainTitle>Rick and Morty Web App</MainTitle>
          <ItemCard/>
        </MainCard>
    </div>
  )
}

export default Home
